Fix storage config for docker-ce
stackhpc/kayobe-original pull request #105
Opened 2018-01-03 09:34 UTC by ktibi

New version of docker-ce use overlay for storage driver by default. 

We need to adapt the check for test if overlay is enable and if devicemapper is configured in kayobe.

2018-01-03 09:59 UTC, markgoddard requested changes

2018-01-03 09:59 UTC, markgoddard commented on ansible/roles/docker/tasks/main.yml
> +  when: "'Data loop file' in docker_info.stdout or ( docker_storage_driver == 'devicemapper' and 'Storage Driver: overlay' in docker_info.stdout )"
This needs to check if the actual storage driver == expected storage driver, not just the specific case of overlay -> devicemapper.

2018-01-03 09:59 UTC, markgoddard commented on ansible/roles/docker/tasks/main.yml
>      - "'Containers: 0' not in docker_info.stdout"
We need to add the check in this task (L99) as well - we can't change the storage driver if images or containers exist.

2018-01-03 09:59 UTC, markgoddard commented on ansible/roles/docker/tasks/main.yml
>      - "'Containers: 0' not in docker_info.stdout"
Optional: To make parsing the output easier, we could decode the docker info output from JSON:

```
 - name: Query docker daemon information
   command: "docker info -f {{ json . }}"
   register: docker_info_json
   changed_when: False

- name: Decode the docker info output
  set_fact:
    docker_info: "{{ docker_info_json | from_json }}"
```

Now the storage driver is accessible via `{{ docker_info.Driver }}`. I'm not sure what the name of the 'Data loop file' field would be in JSON format though, perhaps something under `{{ docker_info.DriverStatus }}`.

2018-01-03 14:03 UTC, markgoddard requested changes

2018-01-03 14:03 UTC, markgoddard commented on ansible/roles/docker/tasks/main.yml
> +    - "'Data loop file' in docker_info.DriverStatus or docker_storage_driver != docker_info.driver"
docker_info.Driver is capitalised for me.

Also, DriverStatus is a list of lists, so the first expression (data loop file) won't ever pass.

2018-01-03 15:01 UTC, markgoddard commented on ansible/roles/docker/tasks/main.yml
> +  when: "'Data loop file' in docker_info.stdout or docker_storage_driver not int docker_info.stdout"
int

2018-01-03 16:14 UTC, ktibi commented on ansible/roles/docker/tasks/main.yml
> +  when: "'Data loop file' in docker_info.stdout or docker_storage_driver not int docker_info.stdout"
done

2018-01-03 16:18 UTC, markgoddard approved these changes
Looks fine, assuming it's been tested?

2018-01-03 16:52 UTC, ktibi commented
I'll test last version tomorow. Wait before merge.

2018-01-04 13:06 UTC, ktibi commented
@markgoddard Works ! can be merged !

2018-01-04 13:30 UTC, markgoddard approved these changes

2018-01-04 13:30 UTC, merged