Support configuring API interface via overcloud inventory file
stackhpc/kayobe-original pull request #114
Opened 2018-01-17 14:19 UTC by dougszumski

I've probably missed something. Once this is good, I can apply it to the other interfaces. It solves my issue with deploying grafana on a multinode host at least.

2018-01-17 14:23 UTC, dougszumski commented
Example overcloud inventory:

```
# Top level controllers group.
[controllers]
# These hostnames must be resolvable from your deployment host
s1 ansible_host=10.0.0.101 api_interface=breno1.7

# Top level compute group.
[compute]
# These hostnames must be resolvable from your deployment host

# Top level monitoring group.
[monitoring]
# These hostnames must be resolvable from your deployment host
s2 ansible_host=10.0.0.102 api_interface=eno1.7

# Top level network group.
[network]
# These hostnames must be resolvable from your deployment host
s1 ansible_host=10.0.0.101 api_interface=breno1.7


```

2018-01-17 14:31 UTC, markgoddard requested changes
Looks good except for the tag.

2018-01-17 14:31 UTC, markgoddard commented on ansible/kolla-ansible.yml
> +    - config
Also needs kolla-ansible tag.

2018-01-17 14:31 UTC, markgoddard commented on ansible/roles/kolla-ansible/defaults/main.yml
> +  - "kolla_api_interface"
Interesting, hadn't thought to use this.

2018-01-17 14:31 UTC, markgoddard commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
I think once all interfaces use this method our inventory lines are going to be a little silly. That said, if this gets you moving again then I'm fine with it for now. After all, what's one more wafer thin mint?

2018-01-17 14:31 UTC, markgoddard commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
I don't think there are any variables that we might want to pass through that should keep their kolla_ prefix, so I guess that's not a problem.

2018-01-17 14:36 UTC, dougszumski commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
Agreed. ```api_interface``` is the only one I need at the moment, so I don't have to convert the others if you'd rather leave those for now.

2018-01-17 14:44 UTC, markgoddard commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
I think there are two options I'd be happy with.
1. Stick with this as a means to an end
2. Support all interfaces and write the variables to an `inventory/host_vars/<host>` file. Also in this case hard code the interface variable names rather than adding them to the pass through vars list.

2018-01-17 14:45 UTC, markgoddard commented
Ah, also the ansible unit tests are failing!

2018-01-17 14:49 UTC, dougszumski commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
Thanks - in the interest of making progress I'll go with 1 for now and create an issue for 2.

2018-01-17 15:01 UTC, dougszumski commented
Tests passed - rebased for merge.

Issue created here for other interfaces: https://github.com/stackhpc/kayobe/issues/115

2018-01-17 15:01 UTC, markgoddard approved these changes

2018-01-18 17:02 UTC, dougszumski commented
Sorry - one extra commit.

2018-01-18 17:17 UTC, markgoddard requested changes

2018-01-18 17:17 UTC, markgoddard commented on ansible/kolla-ansible.yml
> -              required: True
We do need to verify this. Could you add it to the new play above instead?

2018-01-22 15:26 UTC, dougszumski commented on ansible/kolla-ansible.yml
> -              required: True
Thanks - done.

2018-01-22 16:29 UTC, markgoddard requested changes

2018-01-22 16:29 UTC, markgoddard commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
Thinking about this again, I think we're going to have issues with the seed, which currently needs to have an api_interface set in kolla-ansible, even though it's not used: https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/baremetal/tasks/pre-install.yml#L19.

2018-01-23 11:04 UTC, markgoddard approved these changes

2018-01-23 11:04 UTC, markgoddard commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
Actually, it might just work as it is. api_interface for the seed will default to network_interface, which is set to the same value that api_interface was previously in globals.yml.

2018-01-23 11:08 UTC, dougszumski commented on ansible/roles/kolla-ansible/templates/overcloud-top-level.j2
> +{{ host }}{% for hv_name in kolla_overcloud_inventory_pass_through_host_vars %}{% if hv_name in host_hv %} {{ hv_name | regex_replace('^kolla_(.*)$', '\1') }}={{ host_hv[hv_name] }}{% endif %}{% endf
I was just having a dig around and wondering if I needed to explicitly set it - thanks for the pointer.

2018-01-23 11:43 UTC, merged