Support configuring Grafana
stackhpc/kayobe-original pull request #116
Opened 2018-01-19 16:57 UTC by dougszumski

This add supports for running the stackhpc.grafana-conf Ansible
Galaxy role against a monitoring server to configure Grafana
post deployment. This includes:

* Creating an organisation
* Configuring dashboards for the organisation from a git repo
* Configuring datasources for the organisation

2018-01-19 17:04 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +    - name: Clone dashboards
I should probably make the Galaxy role do this, as at the very least it will also be required for using the role for configuring tenant monitoring.

2018-01-19 19:22 UTC, markgoddard commented on kayobe/cli/commands.py
>          self.run_kayobe_playbooks(parsed_args, playbooks)
I've been in the habit of adding unit tests for commands as I change them. Would you mind adding one for overcloud post configure?

2018-01-19 19:22 UTC, markgoddard commented on requirements.yml
> +- src: stackhpc.grafana-conf
Can you add the role to .gitignore?

2018-01-19 19:22 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +#grafana_local_admin_user_name:
nit: I don't normally put the commented out variable in group_vars, only etc/kayobe/

2018-01-19 19:22 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_repo_path: "/var/opt/grafana/"
I tend to use `{{ source_checkout_path }}/grafana`.

2018-01-19 19:22 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +      become: True
Do we need become here? In similar situations I've used the file module with become to ensure the parent directory exists, then cloned the repo without.

2018-01-19 19:22 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +      grafana_conf_grafana_admin_user: "{{ grafana_local_admin_user_name }}"
Should we set this in grafana.conf too?

2018-01-19 19:22 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +workaround_ansible_issue_8743: yes
nit: Don't need this in group_vars as there is always at least one variable.

2018-01-19 19:22 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +grafana_datasources:
Should this default to `{}`?

2018-01-19 19:22 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_repo:
Might we ever need multiple dashboard repos?

2018-01-22 17:00 UTC, dougszumski commented on requirements.yml
> +- src: stackhpc.grafana-conf
Done

2018-01-22 17:01 UTC, dougszumski commented on kayobe/cli/commands.py
>          self.run_kayobe_playbooks(parsed_args, playbooks)
Good idea, i've added a basic test to ensure the correct playbooks are called.

2018-01-22 17:01 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +      grafana_conf_grafana_admin_user: "{{ grafana_local_admin_user_name }}"
Good idea - I was setting it in the config repo, but it's better done in Kayobe.

2018-01-22 17:02 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +      become: True
I've moved this to the ansible role and used file to ensure the dir exists first.

2018-01-22 17:02 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +workaround_ansible_issue_8743: yes
Fixed

2018-01-22 17:02 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +grafana_datasources:
Fixed

2018-01-22 17:03 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_repo_path: "/var/opt/grafana/"
Done

2018-01-22 17:04 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_repo:
Hmm, I can't see a use at the moment. I think it's better to have all the dashboard config in one repo for simplicity. I can always add it later if we need it.

2018-01-22 17:05 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +#grafana_local_admin_user_name:
Done

2018-01-22 17:05 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +    - name: Clone dashboards
Done

2018-01-23 10:34 UTC, markgoddard requested changes
Looking better.

2018-01-23 10:34 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +# A list of datasources to configure. See the stackhpc.grafana-conf role
nit: dict

2018-01-23 10:34 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_path:
Should this be with the other repo variables above?

2018-01-23 10:34 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +        kolla_internal_vip_address: "{{ internal_net_name | net_ip(network_host) }}"
I don't think network_host has been set. If there's no haproxy then I think we can assume that grafana is running on the monitoring node, so we can just use:

`kolla_internal_vip_address: "{{ internal_net_name | net_ip }}"`

2018-01-23 10:34 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +      grafana_conf_grafana_datasources: "{{ grafana_datasources }}"
Have you checked that this is a noop with the defaults?

2018-01-23 10:34 UTC, markgoddard commented on kayobe/cli/commands.py
>          self.run_kayobe_playbooks(parsed_args, playbooks)
Nice, thanks

2018-01-23 10:34 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +grafana_local_admin_user_name: "grafana_admin"
Perhaps we should stick with the kolla default here and override in kayobe-config, since monasca will not be in use by all users.

2018-01-23 10:34 UTC, markgoddard commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_repo_path: "{{ source_checkout_path ~ '/grafana' }}"
nit: grafana-dashboards?

2018-01-23 13:47 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +grafana_local_admin_user_name: "grafana_admin"
Done

2018-01-23 13:47 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_repo_path: "{{ source_checkout_path ~ '/grafana' }}"
Done

2018-01-23 13:47 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +# A list of datasources to configure. See the stackhpc.grafana-conf role
Done

2018-01-23 13:47 UTC, dougszumski commented on ansible/group_vars/all/grafana
> +grafana_monitoring_node_dashboard_path:
Done

2018-01-23 13:48 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +        kolla_internal_vip_address: "{{ internal_net_name | net_ip(network_host) }}"
Done - thanks for the pointer.

2018-01-23 13:49 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +      grafana_conf_grafana_datasources: "{{ grafana_datasources }}"
It runs and doesn't change anything. There are a few tasks in the role which read existing state.

2018-01-23 13:57 UTC, markgoddard approved these changes
Looks good.

2018-01-23 13:58 UTC, dougszumski commented
Thanks for reviewing!

2018-01-23 13:58 UTC, merged

2018-01-24 14:59 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +        relative_path: "{{ grafana_monitoring_node_dashboard_repo_path }}"
What happens here with the defaults? Won't we pass in:

```
     grafana_conf_grafana_dashboard_repo:
        repo:
        version:
        checkout_path: "<default path>"
        relative_path:
```

2018-01-24 16:08 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +        relative_path: "{{ grafana_monitoring_node_dashboard_repo_path }}"
Thanks - that messes up the logic in the ansible role.

2018-01-24 16:30 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +        relative_path: "{{ grafana_monitoring_node_dashboard_repo_path }}"
An alternative would be to just pass through the same dict format from kayobe.

2018-01-24 16:43 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +        relative_path: "{{ grafana_monitoring_node_dashboard_repo_path }}"
That would neater. For the sake of saving time I'm tempted to just set a fact to make sure everything is defined in the grafana role.