roles/cadvisor: Added.
stackhpc/kayobe-original pull request #117
Opened 2018-01-23 12:22 UTC by jpds

2018-01-23 12:46 UTC, markgoddard requested changes
Thanks. Needs group_vars/all/cadvisor and etc/kayobe/cadvisor.yml.

2018-01-23 12:46 UTC, markgoddard commented on ansible/roles/cadvisor/defaults/main.yml
> +#nodeexporter_restart_retries: 10
nit: nodeexporter

2018-01-23 12:46 UTC, markgoddard commented on ansible/roles/cadvisor/defaults/main.yml
> +      - "/:/rootfs"
Is this required? I don't see anywhere where we're using it.

2018-01-23 12:46 UTC, markgoddard commented on ansible/roles/cadvisor/defaults/main.yml
> +      - "/var/lib/docker/:/var/lib/docker:ro"
Why is this required?

2018-01-23 12:46 UTC, markgoddard commented on ansible/roles/cadvisor/defaults/main.yml
> +    published_ports: '8080:8080'
This is the default port for the inspection store. https://github.com/stackhpc/kayobe/blob/d982be21913cd937eb1a8ae9e58ff944411f3b6f/ansible/group_vars/all/inspector#L329

2018-01-23 13:00 UTC, jpds commented on ansible/roles/cadvisor/defaults/main.yml
> +      - "/var/lib/docker/:/var/lib/docker:ro"
For the metrics on filesystem usage by containers.

2018-01-23 13:01 UTC, jpds commented on ansible/roles/cadvisor/defaults/main.yml
> +      - "/:/rootfs"
I took this from https://github.com/google/cadvisor - I imagine its for the machine-wide metrics

2018-01-23 13:58 UTC, markgoddard approved these changes

2018-01-23 15:09 UTC, merged

2018-01-24 11:45 UTC, markgoddard commented on ansible/roles/cadvisor/defaults/main.yml
> +    published_ports: '8080:8080'
Hmm,  I forgot about this issue, and it hasn't been addressed.