Cloud init disable
stackhpc/kayobe-original pull request #122
Opened 2018-02-01 11:00 UTC by diranetafen

Disable Cloud-init to prevent the regeneration of network interface config

2018-02-01 13:06 UTC, markgoddard requested changes
Thanks for this Dirane.

I recently spent some time ensuring that cloud-init works well both for the seed and the overcloud hosts. This change would prevent cloud-init from working. At the least we need to put this behind a flag, e.g. `disable_cloud_init: False`. See https://github.com/stackhpc/kayobe/issues/111 and https://github.com/stackhpc/kayobe/issues/112.

Another (smaller) concern I have is that by disabling cloud-init after the first boot, we require that first boot to be successful. I had a few problems with getting glean and cloud-init to work together. Wouldn't a better solution be to disable or uninstall cloud-init in the image so that it never runs?

Finally, have you tried other methods of disabling cloud-init's network config, such as those listed here: http://cloudinit.readthedocs.io/en/latest/topics/network-config.html#disabling-network-configuration? The simplest I think would be to write a file to /etc/cloud/cloud.cfg.d/disable-net.cfg, containing this:

```
network:
  config: disabled
```

2018-02-01 13:06 UTC, markgoddard commented on kayobe/tests/unit/cli/test_commands.py
> +                    "ansible/disable-cloud-init.yml"
Missing the trailing semicolon - this is why the test is failing.

2018-02-01 13:06 UTC, markgoddard commented on ansible/roles/disable-cloud-init/tasks/main.yml
> +    - "/usr/lib/systemd/system/cloud-init@.service"
I don't see this file on my system.

2018-02-01 13:06 UTC, markgoddard commented on ansible/roles/disable-cloud-init/tasks/main.yml
> +  become: True
Also notify the systemd daemon here?

2018-02-01 13:06 UTC, markgoddard commented on ansible/roles/disable-cloud-init/tasks/main.yml
> +- name: Check for existing CLoud-init systemd services
nit: CLoud-init

2018-02-01 13:06 UTC, markgoddard commented on ansible/roles/disable-cloud-init/handlers/main.yml
> +  become: True
nit: you can use http://docs.ansible.com/ansible/latest/systemd_module.html.

2018-02-01 13:34 UTC, diranetafen commented on ansible/roles/disable-cloud-init/handlers/main.yml
> +  become: True
Thanks for the link ! i will use systemd: daemon_reload=yes

2018-02-01 13:34 UTC, diranetafen commented on ansible/roles/disable-cloud-init/tasks/main.yml
> +- name: Check for existing CLoud-init systemd services
:-) changed

2018-02-01 13:45 UTC, diranetafen commented on ansible/roles/disable-cloud-init/tasks/main.yml
> +    - "/usr/lib/systemd/system/cloud-init@.service"
I have those files in my environment

2018-02-01 13:48 UTC, diranetafen commented on kayobe/tests/unit/cli/test_commands.py
> +                    "ansible/disable-cloud-init.yml"
corrected

2018-02-01 14:13 UTC, markgoddard requested changes

2018-02-01 14:13 UTC, markgoddard commented on ansible/roles/disable-cloud-init/handlers/main.yml
> +  systemd: daemon_reload=yes
Still require become.

2018-02-01 14:13 UTC, markgoddard commented on ansible/roles/disable-cloud-init/handlers/main.yml
> +  systemd: daemon_reload=yes
nit: prefer YAML syntax:

```
systemd:
  daemon_reload: yes
```

2018-02-20 11:15 UTC, diranetafen commented
Hi @markgoddard 
i'm still working on my pull request https://github.com/stackhpc/kayobe/pull/122
And I have a difficulty to understand exactly the problem with it! Because my playbook runs when the overcloud hosts are configured, so the first boot will complete successfully (after provision overcloud).

2018-02-20 11:48 UTC, diranetafen commented
I will make some changes in my code and test it based on this article : https://fatmin.com/2017/10/19/how-to-disable-cloud-init-in-a-rhel-cloud-image/

2018-02-21 12:07 UTC, markgoddard requested changes
This is looking better, thanks.

2018-02-21 12:07 UTC, markgoddard commented on ansible/roles/disable-cloud-init/tasks/main.yml
> +  when: disable_cloud_init | bool
nit: Could you move this `when` to the disable-cloud-init.yml playbook, like this:

```
role: disable-cloud-init
when: disable_cloud_init | bool
```

2018-02-21 12:07 UTC, markgoddard commented on ansible/group_vars/all/overcloud
> +disable_cloud_init: False
Please update etc/kayobe/overcloud.yml.

2018-02-21 14:15 UTC, diranetafen commented on ansible/group_vars/all/overcloud
> +disable_cloud_init: False
Done !

2018-02-21 14:21 UTC, markgoddard approved these changes
I made a small change to etc/kayobe/overcloud.yml to comment out the variable and remove its value. Otherwise, looks good - thanks!

2018-02-21 14:22 UTC, diranetafen commented
Ok @markgoddard  thanks

2018-02-21 14:28 UTC, merged