Add designate config override
stackhpc/kayobe-original pull request #123
Opened 2018-02-07 16:15 UTC by ktibi

2018-02-07 16:38 UTC, markgoddard commented on ansible/roles/kolla-openstack/vars/main.yml
> +    enabled: "{{ kolla_enable_designate }}"
This is fine for `{{ kolla_extra_config_path }}/designate` but will not template `{{ kolla_extra_config_path }}/designate.conf`. Is that ok?

2018-02-07 16:58 UTC, ktibi commented on ansible/roles/kolla-openstack/vars/main.yml
> +    enabled: "{{ kolla_enable_designate }}"
for it's ok but I'll add for designate.conf too

2018-02-07 17:04 UTC, markgoddard commented on ansible/roles/kolla-openstack/vars/main.yml
> +    enabled: "{{ kolla_enable_designate }}"
Also need to add ansible/roles/kolla-openstack/templates/designate.conf.j2. Please test these changes.

2018-02-20 10:41 UTC, ktibi commented
@markgoddard Can you merge ?

2018-02-20 10:53 UTC, markgoddard requested changes
Almost there.

2018-02-20 10:53 UTC, markgoddard commented on ansible/kolla-openstack.yml
> +            - { name: designate, file: designate.conf }
Need to add this at the bottom of this file:

`kolla_extra_designate: "{{ kolla_extra_config.designate | default }}"`

2018-02-20 15:31 UTC, ktibi commented on ansible/kolla-openstack.yml
> +            - { name: designate, file: designate.conf }
it's done.

2018-02-20 15:34 UTC, markgoddard commented on ansible/kolla-openstack.yml
> +            - { name: designate, file: designate.conf }
Thanks.

2018-02-20 16:36 UTC, markgoddard approved these changes

2018-02-20 16:36 UTC, merged