Feature/support configuring grafana
stackhpc/kayobe-original pull request #125
Opened 2018-02-19 17:20 UTC by dougszumski

2018-02-19 17:55 UTC, markgoddard commented on ansible/roles/kolla-openstack/templates/grafana.ini.j2
> -admin_user = {{ grafana_local_admin_user_name }}
Should we set this in globals.yml.j2 in the kolla-openstack role? Would save needing to set it in kayobe-config. Could make it dependent upon kolla_enable_grafana and grafana_local_admin_user_name being set.

2018-02-20 10:09 UTC, markgoddard approved these changes

2018-02-20 10:51 UTC, markgoddard requested changes

2018-02-20 10:51 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +      environment: "{{ openstack_auth_env }}"
@ktibi asked if he could use this feature. As it stands, it depends on the monasca project existing. I think ideally we'd make these two tasks dependent upon a `kolla_enable_monasca` variable. It might be a bit misleading to add that as it stands as it wouldn't do anything. Alternatively we could add `failed_when: False` to ignore errors. What do you think?

2018-02-20 10:54 UTC, markgoddard commented
Also, ansible tests are failing for some reason.

2018-02-20 10:54 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +      environment: "{{ openstack_auth_env }}"
Hmm. I like the idea of being explicit with ```kolla_enable_monasca```. If I put a big comment near it explaining that it's work in progress hopefully it shouldn't be too misleading?

2018-02-20 10:55 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +      environment: "{{ openstack_auth_env }}"
Works for me, and is more future proof.

2018-02-20 12:53 UTC, markgoddard requested changes

2018-02-20 12:53 UTC, markgoddard commented on ansible/roles/kolla-openstack/defaults/main.yml
> +kolla_enable_monasca:
To pass this through to kolla-ansible, it needs to be added to the list in vars/main.yml in this role.

2018-02-20 12:53 UTC, markgoddard commented on ansible/overcloud-grafana-configure.yml
> +      when: kolla_enable_monasca
I think this (and the others below) needs a | bool, as the default "no" evaluates to True.

2018-02-20 13:12 UTC, dougszumski commented on ansible/overcloud-grafana-configure.yml
> +      when: kolla_enable_monasca
Thanks, fixed.

2018-02-20 13:24 UTC, markgoddard requested changes

2018-02-20 13:24 UTC, markgoddard commented on ansible/roles/kolla-openstack/vars/main.yml
> +    enabled: "{{ kolla_enable_monasca }}"
Sorry, I meant the list in kolla-ansible/vars/main.yml. This change will copy config files, but we don't have anything to consume them in kolla-ansible yet.

2018-02-20 13:29 UTC, dougszumski commented on ansible/roles/kolla-openstack/vars/main.yml
> +    enabled: "{{ kolla_enable_monasca }}"
Thanks - that makes more sense. Hopefully it won't be long until we do have something.

2018-02-20 14:49 UTC, dougszumski commented
Ready for review.

2018-02-20 14:51 UTC, markgoddard approved these changes

2018-02-20 14:52 UTC, merged