Add support for Zookeeper
stackhpc/kayobe-original pull request #136
Opened 2018-03-01 19:57 UTC by dougszumski

2018-03-01 20:05 UTC, markgoddard requested changes
Has a kolla-ansible zk role been developed locally?

2018-03-01 20:05 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_zookeeper | bool or kolla_enable_kafka | bool }}"
kolla_enable_kafka needs a default

2018-03-01 20:05 UTC, markgoddard commented on ansible/roles/kolla-openstack/defaults/main.yml
> +kolla_extra_zookeeper:
Need to add these to the enable-everything molecule scenario for kolla-openstack

2018-03-05 11:27 UTC, markgoddard requested changes

2018-03-05 11:27 UTC, markgoddard commented on ansible/roles/kolla-openstack/vars/main.yml
> +    enabled: "{{ kolla_enable_zookeeper }}"
Needs adding to the list in ansible/roles/kolla-openstack/molecule/default/tests/test_default.py and ansible/roles/kolla-openstack/molecule/enable-everything/tests/test_default.py.

2018-03-05 11:53 UTC, dougszumski commented
Need to debug molecule tests...

2018-03-06 12:13 UTC, dougszumski commented
Tests are fixed.

Note to self: squash before merge.

2018-03-06 13:31 UTC, markgoddard approved these changes
Looks good. Thanks for updating the tests.

2018-03-13 16:58 UTC, dougszumski commented
Re-submitted via OpenStack infra: https://review.openstack.org/#/c/552622/

2018-03-13 16:58 UTC, closed without merging