Support copying TLS certificates into place
stackhpc/kayobe-original pull request #137
Opened 2018-03-05 14:45 UTC by yankcrime

This commit handles deployment of TLS certificates on control nodes for use by HAProxy, when `kolla_enable_tls_external` is True and a new variable, `kolla_tls_cert`, is populated with the contents of the certificate file.

2018-03-05 15:02 UTC, markgoddard requested changes
Looking better. Could add a test to verify directory & cert creation in ansible/roles/kolla-ansible/tests/test-extras.yml if you fancy it.

2018-03-05 15:02 UTC, markgoddard commented on ansible/group_vars/all/overcloud
> +
Nice

2018-03-05 15:02 UTC, markgoddard commented on ansible/roles/kolla-ansible/tasks/config.yml
> +        dest: "{{ kolla_config_path }}/certificates/haproxy.pem"
{{ kolla_external_fqdn_cert }}

2018-03-05 15:02 UTC, markgoddard commented on ansible/roles/kolla-ansible/tasks/config.yml
> +        path: "{{ kolla_config_path }}/certificates"
{{ kolla_external_fqdn_cert | dirname }}

2018-03-05 15:02 UTC, markgoddard commented on ansible/roles/kolla-ansible/tasks/config.yml
> +    - kolla_tls_cert is not none
Need a default for this in roles/kolla-ansible/defaults/main.yml

2018-03-05 15:03 UTC, markgoddard commented on ansible/roles/kolla-ansible/tasks/config.yml
> +    - kolla_tls_cert is not none
That is what is causing the test failure: https://travis-ci.org/stackhpc/kayobe/jobs/349325324

2018-03-05 15:25 UTC, yankcrime commented
Ta - I'll see about following up with the missing documentation and tests.

2018-03-08 11:16 UTC, markgoddard approved these changes
Looks good, thanks.

2018-03-13 17:17 UTC, markgoddard commented
@yankcrime can you submit this change via Gerrit?

2018-03-13 18:14 UTC, yankcrime commented
@markgoddard Will do 👍

2018-03-14 10:50 UTC, yankcrime commented
@markgoddard Done: https://review.openstack.org/#/c/552876/

2018-03-14 10:50 UTC, closed without merging