Feature/monasca pike
stackhpc/kayobe-original pull request #163
Opened 2018-09-11 09:46 UTC by dougszumski

2018-09-11 18:11 UTC, markgoddard requested changes

2018-09-11 18:11 UTC, markgoddard commented on ansible/roles/kolla-openstack/vars/main.yml
> +      - persister.conf
Is there a reason to template these specifically? If you remove this ignore attribute then these files will be templated, and you don't need to do the extra stuff, or define a template in kayobe.

Normally we do this if kayobe wants to inject some default config of its own.

2018-09-11 18:11 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_monasca | bool }}"
Should we use this instead: https://review.openstack.org/598520? This will break any binary environments with monasca enabled.

2018-09-11 18:12 UTC, markgoddard commented
Any reason not to do this upstream first and backport?

2018-09-12 08:12 UTC, dougszumski commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_monasca | bool }}"
The StackHPC ones have this set so it shouldn't break them: https://github.com/SKA-ScienceDataProcessor/alaska-kayobe-config/blob/alaska-prod/etc/kayobe/kolla/globals.yml#L7

2018-09-12 08:17 UTC, dougszumski commented on ansible/roles/kolla-openstack/vars/main.yml
> +      - persister.conf
No particular reason yet, I'll update it to use the simpler approach. Thanks.

2018-09-12 09:16 UTC, dougszumski commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_monasca | bool }}"
Now I see that patch is already backported :)

2018-09-26 13:14 UTC, dougszumski commented
Cherry-picked from upstream. Need to remember to use ```cherry-pick -x```...

2018-09-26 13:28 UTC, markgoddard approved these changes

2018-09-26 13:29 UTC, merged