Wallaby: Build overcloud host image directly with DIB
stackhpc/kayobe-original pull request #216
Opened 2021-10-25 14:21 UTC by cityofships

Backporting https://review.opendev.org/c/openstack/kayobe/+/772609

2021-10-26 08:21 UTC, markgoddard requested changes

2021-10-26 08:21 UTC, markgoddard commented on ansible/group_vars/all/dib
> +---
There was a question in the upstream review about naming. It could be quite confusing to change filenames and variable names in our fork. I'd suggest that we at least agree on an approach, and submit it to upstream review, before merging here.

2021-11-29 07:04 UTC, cityofships commented on ansible/group_vars/all/dib
> +---
Now merged upstream

2021-11-29 09:11 UTC, markgoddard approved these changes

2021-11-29 09:47 UTC, merged