Introduce configurable MTU for Docker-encapsulated networking
stackhpc/kayobe-original pull request #3
Opened 2017-03-20 22:04 UTC by oneswig

2017-03-20 22:15 UTC, oneswig commented
Workflow -1 - need to work on better checks in the logic

2017-03-21 09:10 UTC, markgoddard requested changes
Looks good, needs a few changes.

2017-03-21 09:10 UTC, markgoddard commented on ansible/roles/docker/templates/daemon.json.j2
> +  "mtu": 1450,
This should be configurable. The reduced MTU is caused by the iLab gateway. I've also been using MTU 1400 and found that anything greater wouldn't work for my test case of `curl https://galaxy.ansible.com`.

To try to remain DRY we could try to determine the MTU from the kayobe network config. You would do this as follows:

`{{ <network name> | net_mtu }}`

In our case, the relevant network is 'ilab':

`{{ 'ilab' | net_mtu }}`

or alternatively the more abstract network 'role' that is not alaska specific. I'm not sure whether this would always be correct though.

`{{ external_net_name | net_mtu }}`

2017-03-21 09:10 UTC, markgoddard commented on ansible/roles/docker/tasks/main.yml
> +  when: "{{ docker_daemon_json['mtu'] }} != 1450 or {{ docker_daemon_json['storage-driver'] }} != 'devicemapper'"
I don't think we need any slurping here. We can just use the template module to determine if there were any changes. If there were not, the handler won't get triggered.

2017-03-22 09:46 UTC, markgoddard commented on ansible/roles/docker/tasks/main.yml
> +- name: Check Docker state with systemd
Name no longer accurate.

2017-03-22 09:56 UTC, markgoddard commented on ansible/roles/docker/templates/daemon.json.j2
> +  "mtu": {{ external_net_name | net_mtu }},
Sorry, should have explained this in the previous comment. In general I've tried to make the role variables separate from the global variables to make the roles more self-contained and reusable. Sometimes they exist in the global variable space with the same name, sometimes they don't. It usually depends on whether they are shared between multiple plays and roles.

Typically I define all variables required by a role in the defaults files, prefixed by the name of the role to work around ansible's lack of namespacing. Often they're just unset or an empty list or dict. Then in the playbook where the role is used, if there isn't a 1-1 mapping from global to role variable we would do the mapping at that point. For this example, I would do:

ansible/roles/docker/defaults/main.yml:
`docker_daemon_mtu:`

ansible/roles/docker/templates/daemon.json.j2:
`"mtu": {{ docker_daemon_mtu }},`

ansible/docker.yml:
```
  roles:
     - role: docker
       docker_daemon_mtu: "{{ external_net_name | net_mtu }}"
```

2017-03-22 12:13 UTC, markgoddard approved these changes

2017-03-22 12:13 UTC, merged