add credentiels config for registry
stackhpc/kayobe-original pull request #45
Opened 2017-10-25 10:05 UTC by ktibi

This is for push image in dockerhub or a private repo.

credentials conf can add in kayobe-config/etc/kayobe/kolla.yml

2017-10-25 10:19 UTC, markgoddard commented on ansible/roles/kolla-ansible/templates/globals.yml.j2
> +{% if kolla_docker_namespace_username and kolla_docker_namespace_password %}
Does the default evaluate to false now?

2017-10-25 11:02 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +kolla_docker_namespace_username:
Ah, I missed this: it should be `kolla_docker_registry_username` and `kolla_docker_registry_password`.

2017-10-25 13:12 UTC, markgoddard reviewed
Looks fine, just a question about none/None.

2017-10-25 13:12 UTC, markgoddard commented on ansible/container-image-build.yml
> +  pre_tasks:
It's not a problem, but this could equally have worked in tasks. The main difference is pre_tasks are run before roles.

2017-10-25 13:12 UTC, markgoddard commented on ansible/container-image-build.yml
> +      when: kolla_docker_registry_username is not none and kolla_docker_registry_password is not none
Should these be None?

2017-10-25 13:15 UTC, ktibi commented on ansible/roles/kolla-ansible/templates/globals.yml.j2
> +{% if kolla_docker_namespace_username and kolla_docker_namespace_password %}
default value is None.

2017-10-26 08:16 UTC, markgoddard requested changes

2017-10-26 08:16 UTC, markgoddard commented on ansible/container-image-build.yml
> +    kolla_build_log_path: "/var/log/kolla-build.log"
nit: unnecessary whitespace

2017-10-26 08:16 UTC, markgoddard commented on ansible/container-image-build.yml
> +      when: kolla_docker_registry_username is not None and kolla_docker_registry_password is not None
Sorry, you were right here - none is a Jinja test. Test playbook: http://paste.openstack.org/show/624613/

2017-10-26 08:24 UTC, ktibi commented on ansible/container-image-build.yml
> +    kolla_build_log_path: "/var/log/kolla-build.log"
done

2017-10-26 08:25 UTC, ktibi commented on ansible/container-image-build.yml
> +      when: kolla_docker_registry_username is not None and kolla_docker_registry_password is not None
done

2017-10-26 08:33 UTC, markgoddard approved these changes
Looks good, thanks!

2017-10-26 08:38 UTC, merged