add CA conf for private registry
stackhpc/kayobe-original pull request #67
Opened 2017-11-10 14:27 UTC by ktibi

In my kayobe-conf I added :

- kayobe-config/etc/kayobe/docker/ca.crt
- kayobe-config/etc/kayobe/docker.yml :
```
# URL of docker registry
docker_registry: "{{ kolla_docker_registry }}"

# CA of docker registry
docker_registry_ca: "{{ kayobe_config_path }}/docker/certs/ca.crt"
```

2017-11-10 14:52 UTC, markgoddard requested changes

2017-11-10 14:52 UTC, markgoddard commented on ansible/roles/docker/tasks/config.yml
> +  when: kolla_docker_registry is not none and docker_registry_ca is not none
s/kolla_//

2017-11-10 14:52 UTC, markgoddard commented on ansible/roles/docker/tasks/config.yml
> +    dest: "/etc/docker/certs.d/{{ docker_registry }}/ca.crt"
Would it be possible to need more than one CA? Would this be more flexible:

```
# Dict mapping hostnames of registries to an x.509 certificate authority file for that registry. 
docker_registry_ca: {}
```
Example:
```
docker_registry_ca:
  my-registry: "<CA file>"
```

2017-11-10 14:52 UTC, markgoddard commented on ansible/roles/docker/handlers/main.yml
> +- name: reload docker service
Should we always use reload?

2017-11-10 14:56 UTC, ktibi commented on ansible/roles/docker/tasks/config.yml
> +    dest: "/etc/docker/certs.d/{{ docker_registry }}/ca.crt"
normally it's one CA per registry. so one directory by registry.

2017-11-10 15:02 UTC, ktibi commented on ansible/roles/docker/handlers/main.yml
> +- name: reload docker service
yes reload load new CA

2017-11-10 15:04 UTC, markgoddard commented on ansible/roles/docker/tasks/config.yml
> +    dest: "/etc/docker/certs.d/{{ docker_registry }}/ca.crt"
Right, but there could be multiple registries in use by a single docker engine?

2017-11-10 15:05 UTC, markgoddard commented on ansible/roles/docker/handlers/main.yml
> +- name: reload docker service
I mean in the previous task, we restart docker. Should we always do a reload instead of restart? Or is reload not always enough?

2017-11-10 15:12 UTC, ktibi commented on ansible/roles/docker/tasks/config.yml
> +    dest: "/etc/docker/certs.d/{{ docker_registry }}/ca.crt"
hum yes you can, but for now, kayobe use one registry. docker_registry is not a dict mapping.

2017-11-10 15:14 UTC, ktibi commented on ansible/roles/docker/handlers/main.yml
> +- name: reload docker service
If you change conf of docker I don't know if reload it's enough

2017-11-10 16:50 UTC, markgoddard commented on ansible/roles/docker/tasks/config.yml
> +    dest: "/etc/docker/certs.d/{{ docker_registry }}/ca.crt"
That's true, although I think it's still valid as the kayobe services may change but we don't want to keep changing docker. I guess for public registries it won't be necessary, and it's less likely that we would need multiple private registries. We can go this route until we need to change.

2017-11-10 16:51 UTC, markgoddard requested changes

2017-11-10 16:51 UTC, markgoddard commented on ansible/group_vars/all/docker
> +docker_registry_ca:
These two should be added to etc/kayobe/docker.yml.

2017-11-13 09:06 UTC, ktibi commented on ansible/group_vars/all/docker
> +docker_registry_ca:
done

2017-11-13 09:54 UTC, markgoddard approved these changes

2017-11-13 09:54 UTC, merged