add conf regex for build image
stackhpc/kayobe-original pull request #68
Opened 2017-11-10 15:02 UTC by ktibi

2017-11-10 16:48 UTC, markgoddard requested changes

2017-11-10 16:48 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +  - regex: ceilomter
spelling

2017-11-10 16:48 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_central_logging | bool }}"
This should be kolla_enable_elasticsearch

2017-11-10 16:48 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_central_logging | bool }}"
This should be kolla_enable_kibana

2017-11-10 16:48 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_sahara | bool }}"
s/sahara/skydive/

2017-11-10 16:48 UTC, markgoddard commented on ansible/group_vars/all/kolla
>  # List of regular expressions matching names of container images to build for
We need defaults for all of these which match kolla's defaults.

kolla_enable_central_logging isn't used directly, but sets the defaults for elasticsearch and kibana (from kolla-ansible group_vars/all.yml):

```
enable_elasticsearch: "{{ 'yes' if enable_central_logging | bool or enable_freezer | bool or enable_osprofiler | bool or enable_skydive | bool else 'no' }}"
enable_kibana: "{{ 'yes' if enable_central_logging | bool else 'no' }}"
```

2017-11-13 09:18 UTC, ktibi commented on ansible/group_vars/all/kolla
>  # List of regular expressions matching names of container images to build for
done

2017-11-13 09:18 UTC, ktibi commented on ansible/group_vars/all/kolla
> +  - regex: ceilomter
done

2017-11-13 09:20 UTC, ktibi commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_central_logging | bool }}"
done

2017-11-13 09:20 UTC, ktibi commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_central_logging | bool }}"
done

2017-11-13 09:20 UTC, ktibi commented on ansible/group_vars/all/kolla
> +    enabled: "{{ kolla_enable_sahara | bool }}"
done

2017-11-13 09:58 UTC, markgoddard commented on ansible/group_vars/all/kolla
>  # List of regular expressions matching names of container images to build for
Sorry, I wasn't clear - we need to add the defaults with the other kolla_enable_* variables below here, then reference them in this list.

2017-11-13 09:59 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +    enabled: "{{ 'yes' if enable_central_logging | bool or kolla_enable_elasticsearch | bool or enable_freezer | bool or enable_osprofiler | bool or enable_skydive | bool else 'no' }}"
This should just be kolla_enable_elasticsearch, which should be set below to:

`kolla_enable_elasticsearch: {{ 'yes' if kolla_enable_central_logging | bool or kolla_enable_skydive | bool else 'no' }}`

2017-11-13 09:59 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +    enabled: "{{ 'yes' if enable_central_logging | bool or kolla_enable_kibana | bool else 'no' }}"
As above for elasticsearch.

2017-11-13 10:13 UTC, ktibi commented on ansible/group_vars/all/kolla
>  # List of regular expressions matching names of container images to build for
my bad, I do not know read

2017-11-13 14:23 UTC, markgoddard commented on ansible/group_vars/all/kolla
>  # List of regular expressions matching names of container images to build for
The problem we have is that kayobe and kolla-ansible have separate variable namespaces. If you reference a variable in controller_container_image_regex_map, it needs to be defined somewhere. In your kayobe-config I suspect you have all of these variables defined, but in my kayobe-config I don't have kolla_enable_aodh or kolla_enable_ceilometer etc. defined. That's why we need to add default values for all of these like you have for kibana. The goal should be to be able to use the defaults.

You can test this like so:
```
kayobe configuration dump --var-name controller_container_image_regexes
{
    "localhost": [
        "cinder", 
        "cron", 
        "dnsmasq", 
        "fluentd", 
        "glance", 
        "haproxy", 
        "heat", 
        "horizon", 
        "iscsid", 
        "keepalived", 
        "keystone", 
        "kolla-toolbox", 
        "mariadb", 
        "memcached", 
        "neutron-server", 
        "neutron-\\(dhcp\\|l3\\|metadata\\|openvswitch\\)-agent", 
        "nova", 
        "openvswitch", 
        "rabbitmq", 
        "tgtd"
    ]
}
```

If I now make one of the variables undefined, (e.g. add `enabled: "{{ undefined_variable }}"` I get this:
```
kayobe configuration dump --var-name controller_container_image_regexes
{
    "localhost": "{{ controller_container_image_regex_map | selectattr('enabled') | map(attribute='regex') | list }}"
}
```

2017-11-13 15:24 UTC, markgoddard requested changes

2017-11-13 15:24 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +kolla_enable_elasticsearch: "{{ 'yes' if enable_central_logging | bool or enable_freezer | bool or enable_osprofiler | bool or enable_skydive | bool else 'no' }}"
The variables in the `{{ }}` should all have `kolla_` prefixes. They should also all have a default defined.

2017-11-13 15:24 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +kolla_enable_kibana: "{{ 'yes' if enable_central_logging | bool else 'no' }}"
kolla_enable_central_logging

2017-11-13 15:24 UTC, markgoddard commented on ansible/group_vars/all/kolla
> -kolla_enable_ceph: "no"
Need ceph!

2017-11-13 15:24 UTC, markgoddard commented on ansible/group_vars/all/kolla
> -kolla_enable_horizon: "yes"
Need horizon!

2017-11-13 15:24 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +kolla_enable_elasticsearch: "{{ 'yes' if kolla_enable_central_logging | bool or kolla_enable_freezer | bool or kolla_enable_osprofiler | bool or kolla_enable_skydive | bool else 'no' }}"
Freezer and osprofiler still undefined!

2017-11-15 15:35 UTC, markgoddard approved these changes
Looks good, thanks

2017-11-15 15:36 UTC, merged