add ldap conf for keystone
stackhpc/kayobe-original pull request #74
Opened 2017-11-16 10:08 UTC by ktibi

2017-11-16 10:49 UTC, markgoddard commented
Thanks for this @ktibi. I had a thought about this - can we set `recurse: True`  in the two `find` tasks to achieve this and a generally more flexible configuration mechanism?

https://github.com/stackhpc/kayobe/blob/master/ansible/roles/kolla-openstack/tasks/config.yml#L58

2017-11-16 11:40 UTC, markgoddard requested changes

2017-11-16 11:40 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +kolla_enable_keystone_ldap: "no"
I don't think we need this - if the domain files are present we can copy them into place, if not we do nothing.

2017-11-16 16:51 UTC, markgoddard requested changes

2017-11-16 16:51 UTC, markgoddard commented on ansible/group_vars/all/kolla
> +kolla_horizon_keystone_multidomain: "False"
We are just starting to use this flag as well. Can we just keep it outside of kayobe though? If we have to own all configuration options it will be hard to maintain.

You can add this by creating `$KAYOBE_CONFIG_PATH/kolla/globals.yml` and adding it there.

2017-11-17 10:14 UTC, ktibi commented
ok with you about new kolla options

2017-11-17 10:18 UTC, markgoddard approved these changes
Great, thanks

2017-11-17 10:18 UTC, merged