add tag for ceph
stackhpc/kayobe-original pull request #84
Opened 2017-11-27 14:05 UTC by ktibi

2017-11-27 14:25 UTC, markgoddard requested changes
Thanks @ktibi.

2017-11-27 14:25 UTC, markgoddard commented on ansible/ceph.yml
> +  hosts: overcloud
This will match all hosts in the overcloud group, which will include monitoring hosts, and any custom groups in overcloud as well. These hosts won't currently have a ceph_disks variable defined and will fail.

We can either define a default value in group_vars/all for ceph_disks, or use `ceph_disks | default([])` here.

2017-11-27 14:25 UTC, markgoddard commented on ansible/ceph.yml
> +- name: Ensure tag CEPH configuration is applied
How about:

Ensure block devices for use by Ceph are labelled

2017-11-27 14:25 UTC, markgoddard commented on ansible/ceph.yml
> +      register: "disk_info"
nit: Empty line between tasks.

2017-11-27 14:25 UTC, markgoddard commented on ansible/ceph.yml
> +    - name: Fail if the CEPH physical disks have already a partition
Does this make the playbook not idempotent? Ideally we should be able to run this playbook multiple times. Can we not just check that the partition is as expected?

2017-11-27 14:25 UTC, markgoddard commented on ansible/ceph.yml
> +- name: Ensure tag CEPH configuration is applied
Also, minor nit: Ceph isn't capitalised.

2017-11-27 14:32 UTC, ktibi commented on ansible/ceph.yml
> +    - name: Fail if the CEPH physical disks have already a partition
I'll try to modify the check 
if partition name is already kolla tag ==> no fail

2017-11-27 14:37 UTC, markgoddard commented
Should this be integrated with `kayobe overcloud host configure`?

2017-11-27 14:39 UTC, markgoddard commented
Can we also make the playbook name a bit more specific - e.g. `ceph-block-devices.yml`?

2017-11-27 17:05 UTC, markgoddard commented on ansible/ceph.yml
> +        name: "KOLLA_CEPH_OSD_BOOTSTRAP"
Thinking ahead, how would this be extended to support an external journal drive or a cache tier? https://docs.openstack.org/kolla-ansible/ocata/ceph-guide.html

2017-11-27 19:16 UTC, ktibi commented on ansible/ceph.yml
> +        name: "KOLLA_CEPH_OSD_BOOTSTRAP"
yes, I can create second list with a test 
if journal list is empty, use standard conf

2017-11-27 19:22 UTC, ktibi commented
other points : 
- for now, parted module need ansible 2.4 to be able to use feature about partition name. Maybe we can use librairy, or shell command. But with a view to upgrade one day ansible 2.3 to 2.4, use new parted feature is better.
- Need to add partition deletion when deprovision because ceph can be deploy if disks always have old partitions.

2017-11-28 10:12 UTC, markgoddard requested changes

2017-11-28 10:12 UTC, markgoddard commented on ansible/ceph-block-devices.yml
> +      with_items: "{{ ceph_disks }} | default([])"
|default([]) needs to be inside }}.

2017-11-28 10:12 UTC, markgoddard commented on ansible/ceph-block-devices.yml
> +      with_items: "{{ ceph_disks }} | default([])"
As above

2017-11-28 10:12 UTC, markgoddard commented on ansible/ceph-block-devices.yml
> +        label: "{{item.item}}"
Interesting, I haven't seen this used before.

2017-11-28 10:12 UTC, markgoddard commented on ansible/ceph-block-devices.yml
> +          Ensure that each disk in 'ceph_disks' have not a partition.
Grammar nit:

The physical disk {{ item.item }} already has a partition.
Ensure that each disk in 'ceph_disks' does not have any partitions.

2017-11-28 10:12 UTC, markgoddard commented on ansible/ceph-block-devices.yml
> +      with_items: "{{ ceph_disks }} | default([])"
The workaround I suggested previously was essentially this:

```
with_items: "{{ disk_info.results }}"
when: disk_info.partitions | length == 0
```

2017-11-28 22:32 UTC, ktibi commented on ansible/ceph-block-devices.yml
> +      with_items: "{{ ceph_disks }} | default([])"
the job is not idempotent with that. If you have one partition but the good partition, job fail :/

2017-11-29 09:25 UTC, oneswig commented on ansible/ceph-block-devices.yml
> +        number: 1
We have a use case with NVMe drives for Ceph where there are 4 OSDs per NVMe.
It is an assumption that Ceph needs one OSD partition per drive because this makes sense for HDDs.
I am not sure if Kolla makes the same assumption.

2017-11-29 09:30 UTC, ktibi commented on ansible/ceph-block-devices.yml
> +        number: 1
This tasks create a partition for tag the disk. 
After that, kolla remove this partition and create two partitions : one for data, one for journal.
Each OSD container manage one HDD.

2017-11-29 09:32 UTC, oneswig commented on ansible/ceph-block-devices.yml
> +        number: 1
Ah OK, so the limitation is in kolla-ansible.
Do you want an external journal disk, like in https://docs.openstack.org/kolla-ansible/pike/ceph-guide.html#using-an-external-journal-drive

2017-11-29 09:33 UTC, ktibi commented on ansible/ceph-block-devices.yml
> +        number: 1
I will add second list with journal disk, and if list is not empty, kayobe will tag disk with journal tag.

2017-11-29 11:26 UTC, markgoddard commented on ansible/ceph-block-devices.yml
> +      with_items: "{{ ceph_disks }} | default([])"
If there is one partition, the task will not run because `disk_info.partitions | length == 0` is not true.

2018-01-03 11:33 UTC, markgoddard requested changes

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  with_items: "{{ ceph_disks  | default([]) }} + {{ ceph_journal_disks  | default([]) }}"
Don't need the defaults here, as they are set in the defaults file.

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: item.partitions | length > 0 and (item.partitions.0.name != 'KOLLA_CEPH_OSD_BOOTSTRAP' or item.partitions.0.name != 'KOLLA_CEPH_OSD_BOOTSTRAP_FOO_J' or item.partitions.0.name != 'KOLLA_CEPH_O
This line is quite long. You can format `and` operations using a list, and use a variable to simplify the `or`s:
```
when:
  - item.partitions | length > 0
  - item.partitions.0.name not in valid_labels
  vars:
    valid_labels:
      - KOLLA_CEPH_OSD_BOOTSTRAP
      - KOLLA_CEPH_OSD_BOOTSTRAP_FOO_J
      - KOLLA_CEPH_OSD_BOOTSTRAP_FOO
```

However, I think this is actually not quite right. The suffix does not have to be FOO, it can be anything - it is used by kolla-ansible to match the journals to their disks: https://docs.openstack.org/kolla-ansible/ocata/ceph-guide.html.  (code: https://github.com/openstack/kolla-ansible/blob/bf0e8a8d52a7c862f97c5b6baa0863571ec3313f/ansible/roles/ceph/tasks/bootstrap_osds.yml and https://github.com/openstack/kolla/blob/master/docker/kolla-toolbox/find_disks.py).

How about:
```
when:
  - item.partitions | length > 0
  - not item.partitions.0.name.startswith('KOLLA_CEPH_OSD_BOOTSTRAP')
```

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  with_items: "{{ ceph_disks | default([]) }}"
Default not required

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  with_items: "{{ ceph_disks | default([]) }}"
Default not required. Also, should be ceph_journal_disks.

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    name: "{% if ceph_external_journal_enable %} 'KOLLA_CEPH_OSD_BOOTSTRAP_FOO' {% else %} 'KOLLA_CEPH_OSD_BOOTSTRAP' {% endif %}"
If we are using external journals, we need to generate unique suffixes for each disk/journal pair - not FOO. How do we know which journal goes with each disk? Should we just zip the lists together? If we have:

```
ceph_disks: [sda, sdb]
ceph_journal_disks: [sdc, sdd]
```

Then is sdc the journal for sda? Any scheme may need to consider what happens if we add a disk/journal to these lists.

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +
Do we need to check that `ceph_disks | length == ceph_journal_disks | length`?

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_external_journal_enable
Do we need this flag? We could just set `ceph_journal_disks: []`

2018-01-03 11:33 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  parted:
Do we need to ensure that parted is installed?

2018-01-03 11:33 UTC, markgoddard commented on ansible/group_vars/all/compute
> +compute_ceph_journal_enable:
This should have a default value (although I suggest below that it is not required).

2018-01-03 11:33 UTC, markgoddard commented on ansible/group_vars/all/storage
> +      storage_net_name] | unique | list }}
Also storage_mgmt_net_name?

2018-01-03 11:33 UTC, markgoddard commented on ansible/group_vars/all/storage
> +# Storage node CEPH configuration.
nit: Ceph

2018-01-03 11:33 UTC, markgoddard commented on etc/kayobe/compute.yml
> +# compute_ceph_disks:
Needs other variables.

2018-01-03 11:33 UTC, markgoddard commented on etc/kayobe/controllers.yml
> +# controller_ceph_disks:
Needs other variables.

2018-01-03 11:33 UTC, markgoddard commented on etc/kayobe/controllers.yml
>  # Controller node sysctl configuration.
Need to add etc/kayobe/storage.yml

2018-01-03 14:03 UTC, ktibi commented on ansible/group_vars/all/storage
> +      storage_net_name] | unique | list }}
So compute too, because ceph-mon always on controllers.

2018-01-03 14:28 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_external_journal_enable
Can I use : 
{% if ceph_journal_disks == [] %} for L42 ?

2018-01-03 14:33 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    name: "{% if ceph_external_journal_enable %} 'KOLLA_CEPH_OSD_BOOTSTRAP_FOO' {% else %} 'KOLLA_CEPH_OSD_BOOTSTRAP' {% endif %}"
ceph_disks: [sda, sdb]
ceph_journal_disks: 
  - { device: sdc, osd : sda }
  - { device: sdd, osd : sdb }

2018-01-03 14:48 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_external_journal_enable
This is fine:

`{% if ceph_journal_disks %}`

2018-01-09 14:04 UTC, markgoddard requested changes

2018-01-09 14:04 UTC, markgoddard commented on ansible/group_vars/all/storage
> +      storage_net_name] | unique | list }}
Sorry, I don't follow you here. I think we need to add storage_mgmt_net_name to this list, for the Ceph replication network.

2018-01-09 14:04 UTC, markgoddard commented on ansible/group_vars/storage/bios
> +# Dict of monitoring node BIOS options. Format is same as that used by
monitoring

2018-01-09 14:04 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - ceph_disks | length != ceph_journal_disks | length
Is it valid to have some disks with journals and some without?

2018-01-09 14:04 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_external_journal_enable
If this is run after the initial partition creation when Ceph is using the disks, will it work correctly and keep data intact?

2018-01-09 14:04 UTC, markgoddard commented on etc/kayobe/compute.yml
> +#compute_ceph_disks: []
Nit: normally I don't include the default values here.

2018-01-09 14:04 UTC, markgoddard commented on etc/kayobe/storage.yml
> +#storage_ceph_disks: []
Nit: normally I don't include the default values here.

2018-01-09 14:04 UTC, markgoddard commented on ansible/roles/kolla-ceph/defaults/main.yml
> +ceph_external_journal_enable: False
I'm still not convinced this variable is required. I don't feel strongly enough about it to block the review though.

2018-01-09 14:04 UTC, markgoddard commented on ansible/group_vars/all/compute
> +# List of Ceph journal disks.
This needs to describe the variable's data format as it is now non-trivial.

2018-01-09 16:15 UTC, ktibi commented on ansible/group_vars/all/storage
> +      storage_net_name] | unique | list }}
Sorry my comment is not very clear. 
For now, I use a ceph cluster with osd on compute node. storage_mgmt_net_name is not on compute node in kayobe : https://github.com/stackhpc/kayobe/blob/master/ansible/group_vars/all/compute#L18

I think this network is just for ceph-mon. Because replication works on my cluster :/

2018-01-09 16:30 UTC, markgoddard commented on ansible/group_vars/all/storage
> +      storage_net_name] | unique | list }}
Kayobe configures cluster_interface in kolla-ansible using this network. Perhaps you have configured storage_mgmt_net_name == storage_net_name? I think that in general we do need storage_mgmt_net_name on the storage nodes.

2018-01-11 15:56 UTC, ktibi commented on ansible/group_vars/all/storage
> +      storage_net_name] | unique | list }}
yes I used compute_network_interfaces for add both networks on my computes nodes.

2018-01-11 16:04 UTC, ktibi commented on ansible/group_vars/all/compute
> +# List of Ceph journal disks.
in doc or comment before var ?

2018-01-11 16:08 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_external_journal_enable
If disk have already partition, the role fail. 

So I think I need to change with a register and add a condition on other tasks to skip itself if ceph already deployed.

2018-01-11 16:10 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - ceph_disks | length != ceph_journal_disks | length
each OSD need to have a journal ! so if this case, if you use external journal you need to have exactly the same number.

2018-01-11 16:21 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - ceph_disks | length != ceph_journal_disks | length
You can't mix local and external journals?

2018-01-11 16:23 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_external_journal_enable
How do you know if Ceph is already deployed?

2018-01-11 16:23 UTC, markgoddard commented on ansible/group_vars/all/compute
> +# List of Ceph journal disks.
Both, ideally. At least in the comment.

2018-01-17 11:06 UTC, markgoddard requested changes

2018-01-17 11:06 UTC, markgoddard commented on ansible/group_vars/all/compute
> +# Journal variable is not mandatory.
That's better (both format and the comment).

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_disks is defined
ceph_disks should always be defined as it's in defaults.

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  become: True
`when: ceph_disks | length > 0`

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_disks is defined
Do we also need to check the journals?

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - ceph_disks is defined
As above

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  debug:
Should this be fail? If not, need to rename the task and ceph_fail variable.

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: not ceph_fail.skipped
Are you trying to use this to only create the partitions initially? I think there are some problems.

* It would be better to check each disk individually, then disks could be added. You can do this by iterating over ceph_fail.results, and checking item.skipped.
* Due to `item.partitions | length > 0`, this will not create a partition on a disk with no existing partitions.

Maybe it would be better to iterate over disk_info.results here.

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - not item.partitions.0.name.startswith('KOLLA_CEPH_OSD_BOOTSTRAP')
We now know what the partition name should be, so we can match exactly:

`{% if item.journal is defined %} 'KOLLA_CEPH_OSD_BOOTSTRAP_{{ item.osd | basename }}' {% else %} 'KOLLA_CEPH_OSD_BOOTSTRAP' {% endif %}`

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - not ceph_fail.skipped
As above.

2018-01-17 11:06 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: not ceph_fail.skipped
What possibilities are there?
* No partitions -> create a partition
* One or more partitions, first one has the correct label -> do nothing
* One or more partitions, first one has an incorrect label -> error?

Does it matter if there is more than one partition? What does the disk look like after kolla-ansible has run?

2018-01-17 12:57 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  debug:
I change fail to debug because if anyone want to manualy tag disks. I'll rename var

2018-01-17 13:22 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  debug:
Manual tagging should be the same as if kayobe had already tagged the disks and the host configure command was run again, right?

2018-01-17 16:37 UTC, markgoddard requested changes

2018-01-17 16:37 UTC, markgoddard commented on etc/kayobe/storage.yml
> +# List of Ceph disks.
Need the improved comment here.

2018-01-17 16:37 UTC, markgoddard commented on etc/kayobe/controllers.yml
> +# List of Ceph disks.
Need the improved comment here.

2018-01-17 16:37 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: ceph_disks | length > 0
Not required here - if the list is empty there will be no iterations.

2018-01-17 16:37 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +- name: Test if the Ceph OSD disks have already a partition
I don't understand what this debug task is for. The user is unlikely to see this output unless we stop execution of the playbook.

2018-01-17 16:37 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: not ceph_osd_test|skipped
I think we should iterate over disk_osd_info.results in this task, and apply the 'when' conditions here instead. There's no need for the debug task.

2018-01-17 16:37 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - ceph_journal_test|skipped
As above.

2018-01-17 16:37 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - not item | skipped
This won't ever be skipped, will it? Only journals can be skipped.

2018-01-17 16:37 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - ceph_disks | length > 0
ceph_disks | length > 0 not required.

2018-01-17 16:37 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - item.partitions | length > 0
Disks without partitions will be ignored.

2018-01-17 17:15 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +- name: Test if the Ceph OSD disks have already a partition
you want a fail task ?

2018-01-17 17:16 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - not item | skipped
if disk list is total empty ?

2018-01-17 17:17 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - item.partitions | length > 0
yes, if disk have 0 partition it's good. so I skip it.

I use ceph_disks for tagging

2018-01-17 17:28 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - not item | skipped
If the list is emtpy, there will be no items.

2018-01-17 17:31 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +    - item.partitions | length > 0
If it has zero partitions, then you need to add a partition. But you won't because the parted task has when: not ceph_osd_test | skipped

2018-01-25 14:53 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: not ceph_osd_test|skipped
So if I add test here and if disk have other partition, the tagging in skip but kayobe return just OK and SKIP instead of fail ?

2018-02-02 11:43 UTC, markgoddard requested changes

2018-02-02 11:43 UTC, markgoddard commented on kayobe/tests/unit/cli/test_commands.py
> +                    "ansible/ceph-block-devices.yml",
This (correctly) hasn't been added to seed host configure, which is why the test is failing. You can run locally via `tox -e py27`.

2018-02-02 11:43 UTC, markgoddard commented on doc/source/release-notes.rst
>  * Adds tags to plays to support more fine grained configuration using the
pep8 is complaining about trailing whitespace in this file. You can run locally via `tox -e pep8`.

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tests/test-defaults.yml
> +            that: "KOLLA_CEPH_OSD_BOOTSTRAP" in disk_osd_info.results.partitions.0.name
The travis job shows a syntax error here. Should this be (no .results without a with_*):

```
assert:
  that: "disk_osd_info.partitions.0.name == 'KOLLA_CEPH_OSD_BOOTSTRAP'"
```
You should be able to run the job locally with `tox -e ansible`.

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tests/test-defaults.yml
> +            that: "KOLLA_CEPH_OSD_BOOTSTRAP" in disk_osd_info.results.partitions.0.name
You could also (first) assert that `disk_osd_info.partitions | length == 1`

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +- name: Test if the Ceph OSD disks have already a partition
s/Test/Fail/

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +- name: Test if the Ceph journal disks have already a partition
As above

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +# (ktibi) Need to remove parted_kayobe module when kayobe will support ansible 2.4
Also, remember we can't have it in the kayobe repo because it's GPL. I've created a repo: https://github.com/stackhpc/ansible-role-parted-1.1. Can you setup a PR into that repo with the parted module?

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  when: item.partitions == 0
Should be item.partitions | length == 0

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +      part_label: "KOLLA_CEPH_OSD_BOOTSTRAP_{{ item.item.osd | basename }}{{ ansible_hostname }}_J"
Should be:
`part_label: "KOLLA_CEPH_OSD_BOOTSTRAP_{{ part_id }}_J"`

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +      part_label_with_journal: "KOLLA_CEPH_OSD_BOOTSTRAP_{{ part_label_id }}"
Should be:
`part_label_with_journal: "KOLLA_CEPH_OSD_BOOTSTRAP_{{ part_id }}"`

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +      part_id: "{{ item.item.osd | basename }}{{ ansible_hostname }}"
If there is a better name for this variable, feel free to change it.

2018-02-02 11:43 UTC, markgoddard commented on ansible/roles/kolla-ceph/tasks/config.yml
> +  parted_kayobe:
Maybe name this parted_1_1?

2018-02-02 15:31 UTC, ktibi commented on ansible/roles/kolla-ceph/tasks/config.yml
> +      part_id: "{{ item.item.osd | basename }}{{ ansible_hostname }}"
yes it's not a partition but the ID of OSD.

2018-02-06 16:51 UTC, markgoddard commented on ansible/roles/kolla-ceph/tests/test-defaults.yml
> +          parted_kayobe:
Still using parted_kayobe here.

2018-02-22 14:50 UTC, markgoddard approved these changes
Tests are now passing.

2018-02-22 14:51 UTC, merged