[Vagrant] Support for VMware Fusion, fixes for container image builds
stackhpc/kayobe-original pull request #85
Opened 2017-11-28 18:26 UTC by yankcrime

This PR:

* Refactors the Vagrantfile somewhat and introduces support for VMware Fusion;
* In order to support HGFS for the above, it also switches the default Vagrant boxes to be ones hosted under the [StackHPC organisation](https://app.vagrantup.com/stackhpc/boxes/centos-7) on Vagrant Cloud.  These have been built with the relevant guest additions which are missing from the default CentOS images due to licensing shenanigans;
*  Adds the development VM to a `container-image-builders` group so that images can be built.

2017-11-29 10:28 UTC, markgoddard requested changes
Looks good, thanks.

2017-11-29 10:28 UTC, markgoddard commented on Vagrantfile
> +  config.vm.box = 'stackhpc/centos-7'
How did you build this box? Is there a Vagrantfile we can add for if we ever need to rebuild it?

2017-11-29 10:28 UTC, markgoddard commented on Vagrantfile
> -  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
We found that we need this, or else we don't get a persistent share. Can you add it inside the virtualbox provider?

2017-11-29 10:28 UTC, markgoddard commented on dev/dev-hosts
> +controller1 ansible_host=192.168.33.3
There's also one in dev/dev-vagrant-network-allocation.yml which is controller0. I think the Vagrantfile was probably the odd one out, but it doesn't matter too much which way we go.

2017-11-29 10:53 UTC, yankcrime commented on Vagrantfile
> +  config.vm.box = 'stackhpc/centos-7'
They're generated via Packer using a fork of Boxcutter's [CentOS templates](https://github.com/boxcutter/centos).  I'll move the fork to sit under StackHPC's organisation so that we've all got visibility of how these are built.

2017-11-29 10:55 UTC, yankcrime commented on Vagrantfile
> -  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
You'll get a persistent share using this updated image - I believe it's supposed to be the default as long as Vagrant can detect present of the VirtualBox guest tools in the VM as it's booting, otherwise it falls back to rsync.  Happy to add this back in though so it's explicit 👍

2017-11-29 11:20 UTC, markgoddard commented on Vagrantfile
> -  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
As long as it works, I don't mind!

2017-11-29 11:21 UTC, markgoddard commented on Vagrantfile
> +  config.vm.box = 'stackhpc/centos-7'
:+1:

2017-11-29 11:23 UTC, markgoddard commented
Are you able to test this with virtualbox, or shall I do it?

2017-11-29 11:37 UTC, yankcrime commented
I've tested it on a machine I have here running Ubuntu 17.10 and VirtualBox 5.1 but it'd be great if you could give it a go as well - especially if you're running different versions to me, just to make sure the guest additions are detected OK and that shared folders Just Work ™:

```
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.30 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => /home/nick/src/kayobe
```

2017-11-29 11:37 UTC, yankcrime commented on dev/dev-hosts
> +controller1 ansible_host=192.168.33.3
Done!

2017-11-29 17:42 UTC, markgoddard commented on Vagrantfile
> -  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
It worked for me without, but then looking at the commit history, JohnG added it. It's possible that use of the vbguest plugin means that it will now always work. Perhaps @JohnGarbutt could verify that it works for him if we're going to remove it?

2017-11-29 17:43 UTC, markgoddard approved these changes
I've deployed a VM on my laptop with these changes and all worked well.

There's still a question around the vagrant shared folder for JohnG to answer but otherwise I'm happy.

2017-11-29 17:45 UTC, markgoddard commented on Vagrantfile
> -  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
Here's the commit: https://github.com/stackhpc/kayobe/commit/42605939a4f911fb3bf777e2d80e91cf3f5aa710

2017-12-05 13:37 UTC, markgoddard commented
I don't see JohnG replying any time soon, so let's merge this.

2017-12-05 13:37 UTC, merged